# Generated by Django 4.0.5 on 2022-06-17 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demographics',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name', models.CharField(max_length=255)),
                ('tx_date', models.DateField(blank=True, null=True)),
                ('tx_time', models.TimeField(blank=True, null=True)),
                ('tx_description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatment',
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_name', models.CharField(max_length=255)),
                ('labname1', models.CharField(max_length=50)),
                ('labval1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labname2', models.CharField(max_length=50)),
                ('labval2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labname3', models.CharField(max_length=50)),
                ('labval3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labname4', models.CharField(max_length=50)),
                ('labval4', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labname5', models.CharField(max_length=50)),
                ('labval5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labname6', models.CharField(max_length=50)),
                ('labval6', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labname7', models.CharField(max_length=50)),
                ('labval7', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labname8', models.CharField(max_length=50)),
                ('labval8', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labname9', models.CharField(max_length=50)),
                ('labval9', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnostics',
            },
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(max_length=255)),
                ('screen_date', models.DateField(blank=True, null=True)),
                ('cancer_dx', models.CharField(max_length=255)),
                ('cancderdx_date', models.DateField(blank=True, null=True)),
                ('eligibility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.demographic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'baseline',
            },
        ),
    ]
