# Generated by Django 4.0.5 on 2022-06-17 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseline',
            old_name='eligibility_id',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.demographic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.demographic'),
            preserve_default=False,
        ),
    ]
